language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-jade-preview' ]; then cd .. && eval "mv $currentfolder generator-jade-preview" && cd generator-jade-preview; fi
